### ISSUE TITLE
[LeetCode] 1431. Kids With the Greatest Number of Candies

### ISSUE THREAD

**Issue by harry-cluml** [harry-cluml/rust-practice#15]
## Tasks
- [ ] Implement the `solve` function.
- [ ] Write the provided examples as test cases.
- [ ] LeetCode solution accepted?

## References
- [LeetCode Problem Link](https://leetcode.com/problems/kids-with-the-greatest-number-of-candies/description/)
